Fix with_traceback calls (#2)
What?
=====

* Fix calls to `with_traceback` to include a traceback parameter

Why?
=====

* We experienced errors with our errors:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File ".../python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".../python3.6/site-packages/knowledge_repo/app/index.py", line 43, in index_sync_loop
    update_index(check_timeouts=False)
  File ".../python3.6/site-packages/knowledge_repo/app/models.py", line 139, in wrapped
    raise e.with_traceback()
TypeError: with_traceback() takes exactly one argument (0 given)
```

This doesn't do much, but clean up the error logs a bit so we can more quickly pin down the real problem.

Test Plan
========

- [x] Trigger an error and ensure the traceback no longer shows up.

For our current deployment, booting with more than one worker triggers this problem since we have the following error occur on startup:

```
Process Process-1:1:
Traceback (most recent call last):
  File ".../python3.6/site-packages/knowledge_repo/app/models.py", line 134, in wrapped
#!/bin/bash
    return function(*args, **kwargs)
  File ".../python3.6/site-packages/knowledge_repo/app/index.py", line 141, in update_index
    current_repo.update()
  File ".../python3.6/site-packages/knowledge_repo/repositories/gitrepository.py", line 144, in update
    self.git.branches[branch].checkout()
  File ".../python3.6/site-packages/git/refs/head.py", line 219, in checkout
    self.repo.git.checkout(self, **kwargs)
  File ".../python3.6/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File ".../python3.6/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File ".../python3.6/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git checkout master
  stderr: 'fatal: Unable to create '.../repo/.git/index.lock': File exists.
```